default_platform(:android)

platform :android do
  desc "Upload a new release to the Closed Testing (Alpha) track"
  lane :deploy do
    upload_to_play_store(
      track: 'alpha',
      release_status: 'completed',
      aab: 'app/release/app-release.aab',
      package_name: 'com.scribblefit.app',
      json_key: 'play-store-key.json'
    )
  end
end
