package com.scribblefit.feature.scribble.domain.usecase

import com.scribblefit.core.model.CurrentDate
import com.scribblefit.core.model.Scribble
import com.scribblefit.core.model.ScribbleStatus
import com.scribblefit.feature.scribble.domain.ScribbleRepository

class AddScribbleUseCase(
    private val repository: ScribbleRepository
) {
    suspend operator fun invoke(text: String, date: CurrentDate) {
        val scribble = Scribble(
            id = 0, // Generated by DB
            rawText = text,
            status = ScribbleStatus.PENDING,
            createdAt = date.startOfDayInMillis
        )
        repository.insertScribble(scribble)
    }
}
