ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ com.scribblefit.api.AppKt.module ]
    }
}

scribblefit {
    config {
        promptVersion = "1.0.0"
        promptVersion = ${?PROMPT_VERSION}
        promptText = "You are a workout log parser. Your task is to take raw text from a user's workout log and convert it into a structured JSON format. Follow the schema strictly."
        promptText = ${?PROMPT_TEXT}
    }
}
