package com.scribblefit.feature.canvas.domain

import com.scribblefit.core.model.Scribble
import com.scribblefit.core.model.ScribbleStatus
import com.scribblefit.feature.scribble.domain.ScribbleRepository
import java.time.LocalDate
import java.time.ZoneOffset

class AddScribbleUseCase(
    private val repository: ScribbleRepository
) {
    suspend operator fun invoke(text: String, date: LocalDate) {
        val timestamp = date.atStartOfDay().toInstant(ZoneOffset.UTC).toEpochMilli()
        val scribble = Scribble(
            id = 0, // Generated by DB
            rawText = text,
            status = ScribbleStatus.PENDING,
            createdAt = timestamp
        )
        repository.insertScribble(scribble)
    }
}
