package com.scribblefit.feature.ai.data.entity

import com.scribblefit.core.model.CurrentDate
import com.scribblefit.core.model.Exercise
import com.scribblefit.core.model.Set
import kotlinx.serialization.Serializable
import java.time.LocalDate

@Serializable
data class ExerciseDto(
    val name: String,
    val muscleGroup: String,
    val sets: List<SetDto>,
)

@Serializable
data class SetDto(
    val setNumber: Int,
    val reps: Int,
    val weight: Float? = null,
    val rpe: Float? = null,
    val notes: String? = null
)

fun ExerciseDto.toDomain(): Exercise = Exercise(
    id = 0L, // Placeholder, as ID will be generated by the database
    canonicalName = name,
    muscleGroup = muscleGroup,
    sets = sets.map { it.toDomain() },
    createdAt = CurrentDate(LocalDate.now()).startOfDayInMillis,
    isDraft = true
)

fun SetDto.toDomain(): Set = Set(
    id = 0L, // Placeholder, as ID will be generated by the database
    setNumber = setNumber,
    reps = reps,
    weight = weight,
    rpe = rpe,
    notes = notes
)