package com.scribblefit.feature.ai.data.entity

import com.scribblefit.core.model.CurrentDate
import com.scribblefit.core.model.Exercise
import com.scribblefit.core.model.Set
import kotlinx.serialization.Serializable
import java.time.LocalDateTime

@Serializable
data class WorkoutResponseDto(
    val exercises: List<ExerciseDto>
)

@Serializable
data class ExerciseDto(
    val canonicalName: String,
    val muscleGroup: String,
    val sets: List<SetDto>,
    val estimated1RM: Float? = null,
    val intensity: Float? = null
)

@Serializable
data class SetDto(
    val setNumber: Int,
    val reps: Int,
    val weight: Float? = null,
    val rpe: Float? = null,
    val notes: String? = null
)

fun ExerciseDto.toDomain(): Exercise = Exercise(
    id = 0L, // Placeholder, as ID will be generated by the database
    canonicalName = canonicalName,
    muscleGroup = muscleGroup,
    sets = sets.map { it.toDomain() },
    createdAt = CurrentDate(LocalDateTime.now()).millis,
    isDraft = true
)

fun SetDto.toDomain(): Set = Set(
    id = 0L, // Placeholder, as ID will be generated by the database
    setNumber = setNumber,
    reps = reps,
    weight = weight,
    rpe = rpe,
    notes = notes
)